[package]
name = "check_errors"
version = "0.1.0"
authors = ["David Schultz <davids24@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"

[dev-dependencies]
assert_cmd = "1.0"
